[phases.setup]
nixPkgs = ["nodejs_22", "chromium"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
NODE_ENV = "production"
